import type { ReactNode } from "react";
import "./globals.css"
import "@radix-ui/themes/styles.css";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: ReactNode }) {
    return children
}
